"""Third Migration

Revision ID: 52f7bedf4f6d
Revises: c92ece5f465e
Create Date: 2022-05-13 08:40:58.735534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f7bedf4f6d'
down_revision = 'c92ece5f465e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizza', sa.Column('description', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pizza', 'description')
    # ### end Alembic commands ###
